# Generated by Django 4.2.7 on 2025-10-21 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name or number (e.g., Room 101, Lab A)', max_length=100, unique=True)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LABORATORY', 'Laboratory'), ('AUDITORIUM', 'Auditorium'), ('MEETING_ROOM', 'Meeting Room'), ('CONFERENCE_HALL', 'Conference Hall'), ('STUDY_ROOM', 'Study Room'), ('OTHER', 'Other')], default='CLASSROOM', max_length=20)),
                ('building', models.CharField(help_text='Building name or location', max_length=100)),
                ('floor', models.CharField(blank=True, help_text='Floor number', max_length=20, null=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of people', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Additional information about the room', null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under Maintenance'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_computer', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False, verbose_name='Has Air Conditioning')),
                ('has_audio_system', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, help_text='Room photo', null=True, upload_to='rooms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['building', 'name'],
            },
        ),
    ]
