# Generated by Django 5.2.6 on 2026-02-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date de fin pour les réservations sur plusieurs jours (laisser vide pour une journée)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(help_text='Date de début de la réservation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(help_text='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(help_text='Heure de début'),
        ),
    ]
